version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.15.0
    - 4.15.1
    - 4.16.1
    - 4.17.0
    - 4.19.0
    - 4.20.0
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.15.0
    - 4.15.1
    - 4.16.1
    - 4.17.0
    - 4.19.0
    - 4.20.0
  - dependency-name: eslint
    versions:
    - 7.21.0
    - 7.23.0
  - dependency-name: semantic-release
    versions:
    - 17.4.0
    - 17.4.1
  - dependency-name: typescript
    versions:
    - 4.2.2
  - dependency-name: ts-jest
    versions:
    - 26.5.2
